# Generated by Django 3.2.5 on 2021-10-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_transaction_account'),
        ('users', '0002_userbankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
